// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/mfa/challenge.ts";
import * as $5 from "./routes/api/mfa/enroll.ts";
import * as $6 from "./routes/api/sign-in.ts";
import * as $7 from "./routes/api/sign-out.ts";
import * as $8 from "./routes/api/sign-up.ts";
import * as $9 from "./routes/dashboard.tsx";
import * as $10 from "./routes/enroll.tsx";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/sign-in.tsx";
import * as $13 from "./routes/sign-up.tsx";
import * as $14 from "./routes/verify.tsx";
import * as $$0 from "./islands/auth-form.tsx";
import * as $$1 from "./islands/enroll-mfa.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/mfa/challenge.ts": $4,
    "./routes/api/mfa/enroll.ts": $5,
    "./routes/api/sign-in.ts": $6,
    "./routes/api/sign-out.ts": $7,
    "./routes/api/sign-up.ts": $8,
    "./routes/dashboard.tsx": $9,
    "./routes/enroll.tsx": $10,
    "./routes/index.tsx": $11,
    "./routes/sign-in.tsx": $12,
    "./routes/sign-up.tsx": $13,
    "./routes/verify.tsx": $14,
  },
  islands: {
    "./islands/auth-form.tsx": $$0,
    "./islands/enroll-mfa.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
